#!/bin/sh

PATH=/usr/bin:/bin

dir="/var/tmp/checkupdates-cron.$USER"

mkdir -p "$dir"

if [ -f "$dir/current" ]; then
    mv "$dir/current" "$dir/last"
fi

checkupdates > "$dir/current"

if ! diff "$dir/current" "$dir/last" >/dev/null 2>&1; then
    cat "$dir/current" >&2
fi
